- action:
  - alias: ''
    data:
      entity_id: switch.wemo_mini
    service: switch.turn_on
  alias: Turn on the Living Room Lights when I get home
  condition: []
  id: '999'
  trigger:
  - entity_id: device_tracker.phone_phone
    event: enter
    platform: zone
    zone: zone.home
- action:
  - alias: ''
    data: {}
    service: light.turn_on
  - delay: 00:05:00
  - data: {}
    service: light.turn_off
  alias: Turn on the Lights when I get home
  condition: []
  id: '1512613072232'
  trigger:
  - entity_id: device_tracker.phone_phone
    event: enter
    platform: zone
    zone: zone.home
- action:
  - alias: ''
    data: {}
    service: light.turn_off
  alias: Turn off the Lights when I leave Home
  condition: []
  id: '1513967584329'
  trigger:
  - entity_id: device_tracker.phone_phone
    event: leave
    platform: zone
    zone: zone.home
- action:
  - data:
      entity_id: switch.light_switch_garage_switch
    service: switch.turn_off
  alias: Turn off the Garage Light
  condition:
  - condition: state
    entity_id: sensor.garage_door
    state: Closed
  - condition: state
    entity_id: sensor.garage_door_tilt
    state: Closed
  - condition: state
    entity_id: sensor.garage_motion
    state: No Motion
  id: '1516566420558'
  trigger:
  - entity_id: sensor.garage_door
    from: Open
    platform: state
    to: Closed
  - entity_id: sensor.garage_door_tilt
    from: Open
    platform: state
    to: Closed
  - entity_id: sensor.garage_motion
    from: Motion
    platform: state
    to: No Motion
- action:
  - data:
      entity_id: switch.light_switch_garage_switch
    service: switch.turn_on
  alias: Turn on the Garage Light
  condition: []
  id: '1516566420559'
  trigger:
  - entity_id: sensor.garage_door
    from: Closed
    platform: state
    to: Open
  - entity_id: sensor.garage_door_tilt
    from: Closed
    platform: state
    to: Open
  - entity_id: sensor.garage_motion
    from: No Motion
    platform: state
    to: Motion
