- action:
  - alias: ''
    data:
      entity_id: switch.wemo_mini
    service: switch.turn_on
  alias: Turn on the Living Room Lights when I get home
  condition: []
  id: '999'
  trigger:
  - entity_id: device_tracker.phone_phone
    event: enter
    platform: zone
    zone: zone.home
- action:
  - alias: ''
    data:
      entity_id: light.porch
    service: light.turn_on
  - delay: 00:05:00
  - data:
      entity_id: light.porch
    service: light.turn_off
  alias: Turn on the Lights when I get home
  condition: []
  id: '1512613072232'
  trigger:
  - entity_id: device_tracker.phone_phone
    event: enter
    platform: zone
    zone: zone.home
- action:
  - alias: ''
    data: {}
    service: light.turn_off
  alias: Turn off the Lights when I leave Home
  condition: []
  id: '1513967584329'
  trigger:
  - entity_id: device_tracker.phone_phone
    event: leave
    platform: zone
    zone: zone.home
- action:
  - data:
      entity_id: switch.light_switch_garage_switch
    service: switch.turn_off
  alias: Turn off the Garage Light
  condition:
  - condition: state
    entity_id: sensor.garage_door
    state: Closed
  - condition: state
    entity_id: sensor.garage_door_tilt
    state: Closed
  - condition: state
    entity_id: sensor.garage_motion
    state: Clear
  id: '1516566420558'
  trigger:
  - entity_id: sensor.garage_door
    from: Open
    platform: state
    to: Closed
  - entity_id: sensor.garage_door_tilt
    from: Open
    platform: state
    to: Closed
  - entity_id: sensor.garage_motion
    from: Occupied
    platform: state
    to: Clear
- action:
  - data:
      entity_id: switch.light_switch_garage_switch
    service: switch.turn_on
  alias: Turn on the Garage Light
  condition: []
  id: '1516566420559'
  trigger:
  - entity_id: sensor.garage_door
    from: Closed
    platform: state
    to: Open
  - entity_id: sensor.garage_door_tilt
    from: Closed
    platform: state
    to: Open
  - entity_id: sensor.garage_motion
    from: No Motion
    platform: state
    to: Motion
- action:
  - data:
      message: Your system has been armed.
      target:
      - '#general'
    service: notify.slack_notifier
  alias: Arm Alarm
  condition: []
  id: '1517092813989'
  trigger:
  - entity_id: input_boolean.alarm
    from: 'off'
    platform: state
    to: 'on'
- action:
  - data:
      message: Your system has been disarmed.
      target:
      - '#general'
    service: notify.slack_notifier
  alias: Disarm Alarm
  condition: []
  id: '1517092895408'
  trigger:
  - entity_id: input_boolean.alarm
    from: 'on'
    platform: state
    to: 'off'
- action:
  - data:
      message: 'ALARM TRIGGERED: Garage Side Door Opened!'
      target:
      - '#general'
    service: notify.slack_notifier
  alias: 'ALARM: Garage Side Door'
  condition:
  - condition: state
    entity_id: input_boolean.alarm
    state: 'on'
  id: '1517093518812'
  trigger:
  - entity_id: sensor.garage_door
    from: Closed
    platform: state
    to: Open
- action:
  - data:
      message: 'ALARM TRIGGERED: Garage Door Opened!'
      target:
      - '#general'
    service: notify.slack_notifier
  alias: 'ALARM: Garage Door'
  condition:
  - condition: state
    entity_id: input_boolean.alarm
    state: 'on'
  id: '1517093518813'
  trigger:
  - entity_id: sensor.garage_door_tilt
    from: Closed
    platform: state
    to: Open
- action:
  - data:
      message: 'ALARM TRIGGERED: Living Room Motion Detected! https://5329drew.duckdns.org:8123/states/group.cameras'
      target:
      - '#general'
    service: notify.slack_notifier
  alias: 'ALARM: Living Room Motion Detector'
  condition:
  - condition: state
    entity_id: input_boolean.alarm
    state: 'on'
  id: '1517093518814'
  trigger:
  - entity_id: binary_sensor.living_room_occupancy
    from: 'off'
    platform: state
    to: 'on'
- action:
  - data:
      message: 'ALARM TRIGGERED: Living Room Motion Detected!'
      target:
      - '#general'
    service: notify.slack_notifier
  alias: 'ALARM: Living Room Motion Detector'
  condition:
  - condition: state
    entity_id: input_boolean.alarm
    state: 'on'
  id: '1517093518814'
  trigger:
  - entity_id: sensor.garage_motion
    from: Clear
    platform: state
    to: Occupied
- action:
  - data:
      entity_id: switch.3d_printer
    service: switch.turn_off
  alias: Turn off 3D Printer when complete
  condition: []
  id: '1517662945541'
  trigger:
  - entity_id: sensor.octoprint_job_percentage
    platform: state
    to: '100'
- action:
  - data:
      message: 'ERROR: Print Error Detected! https://5329drew.duckdns.org:8123/states/group.octoprint'
      target:
      - '#3dprints'
    service: notify.slack_notifier
  alias: 'ALERT: Printing Error'
  condition: []
  id: '1517696090559'
  trigger:
  - entity_id: binary_sensor.octoprint_printing_error
    from: 'Off'
    platform: state
    to: 'On'
